#!/bin/bash

gawk ' 
	$1==$2 && $1 != "?" && $2 != "?" {
		printf ++num ";"
		for (r=3; r<=NF-1; r++) {
			printf $r";"
		}
		print $NF
		
		freq[NF]++
	}
	
END { 
	for (n in freq) 
		print freq[n] " riviä, joilla on " n " saraketta"
}
' ad.data > data2.csv
